### ISSUE TITLE
release on packagist

### ISSUE THREAD

**Issue by maaarghk** [mention-me/magento2-integration#11]
Hey,

Having issues on a CI box where entire composer install fails due to going over github rate limits due to the custom vcs repository. Please publish the module on packagist to avoid this.

Cheers,

M

**Comment by maaarghk** [comment]
@matiasm  Are you the PHP guy here now? This should be a quick thing - pretty annoying having pipelines failing because of Github rate limits.

**Comment by maaarghk** [comment]
@alexoanea @joesaunderson please

**Comment by joesaunderson** [comment]
> @alexoanea @joesaunderson please

Hey @maaarghk, I'm not actually involved with this package, but I've raised this internally. 

I'll get an answer for you early next week, thanks for raising!

**Comment by edhgoose** [comment]
Hi @maaarghk - thanks for your patience here. I've published the package on packagist under the name https://packagist.org/packages/mention-me/magento2-module

This means we've renamed the package in the process. We did this as the name was generic and we may want to publish other packages in the future.

Other than that, nothing else has changed.

Can you confirm this new package on packagist works for you?

**Comment by edhgoose** [comment]
Hi @maaarghk - it looks like we've seen an install on Packagist so I believe this is working for you now.

We'll close the issue - please don't hesitate to get in touch if you still require assistance.
