### ISSUE TITLE
Referee Integration not working on checkout

### ISSUE THREAD

**Issue by pushonmax** [mention-me/magento2-integration#4]
Installed extension and testing on M2 Luma, referrals appearing as intended on homepage and product page, but not on checkout. 

I can confirm the scripts have loaded (**https://static-demo.mention-me.com/js/compiled/mentionme-tag-library-v2-b920ec1.js** and **static/frontend/Magento/luma/en_US/MentionMe_MentionMe/js/view/checkout/referee.js**), the **mmwrapper** div is also loaded, yet nothing is being inserted into it. Tried every setting on the **position on page** setting as well.

**Comment by alexoanea** [comment]
@pushonmax can you share a link to the demo/staging environment where you've installed the extension so I can have a look at the checkout page?

**Comment by pushonmax** [comment]
Hi @alexoanea ,

I will email you the details

**Comment by alexoanea** [comment]
Issue was that the Magento store locale was not configured to match the Mention Me configuration
